### ISSUE TITLE
mapping in nao robot

### ISSUE THREAD

**Issue by bashaerqr** [max-leuthaeuser/naoservice#1]
Hi
it is my first time in robot programming and I am working in the nao robot, my question is
how can I do mapping in nao by python?

can you help me, please?

**Comment by max-leuthaeuser** [comment]
Hi!

If you work directly with Python you do not need `naoservice` at all.
Aldebaran Robotics already provides a fully featured Python SDK.

`naoservice` is only useful to have access to your robot from programming languages not directly supported by Aldebaran yet.

Cheers,
Max

**Comment by bashaerqr** [comment]
I connect nao robot to my python shell with naoqi , it works for some codes , now i want to do mapping for a room by python , how can I do it without Ros , I do not have any idea .

is there any method to create mapping for nao robot by python?

**Comment by bashaerqr** [comment]
and I want to reach destination in static place

**Comment by max-leuthaeuser** [comment]
Mapping is no concern of `naoservice`. I can't help you with this.
